server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://finalprojectdb.mysql.database.azure.com:3306/finalserver
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: minhyoung
    password: Kim@1002

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:change-me}        # 환경변수 권장
  access-token-validity-seconds: 900     # 15분
  refresh-token-validity-days: 14        # 14일